### PR TITLE
Don't let the ChainDB add a dummy genesis EBB on startup

### LINKED ISSUE #87: Byron-Proxy failing to sync from clean slate
**Issue**

`Cardano-Byron-Proxy` is failing to sync when it's started from a clean slate. This is happening for both `tags/1.0.3` and `master` on both `staging` and `mainnet`. 

The first error that occurs once is: 

```
[cardano_byron_proxy.main.client:Info:62] [2020-01-20 10:51:17.77 UTC] Attempting to download chain with hash AbstractHash 0bdaaa4fe38239c8fa64dfb208ff80886ef8f5dd49d9b532948809682487c85a from NodeId 13.250.233.196:3000:0
[cardano_byron_proxy.diffusion.outboundqueue.self:Debug:62] [2020-01-20 10:51:17.77 UTC] inFlight = fromList []
[cardano_byron_proxy.diffusion.outboundqueue.self:Debug:62] [2020-01-20 10:51:17.77 UTC] message MsgRequestBlocks (fromList [NodeId 13.250.233.196:3000:0]) enqueued to [NodeId 13.250.233.196:3000:0]
[cardano_byron_proxy.diffusion.outboundqueue.self:Debug:75] [2020-01-20 10:51:17.78 UTC] sending MsgRequestBlocks (fromList [NodeId 13.250.233.196:3000:0]) to NodeId 13.250.233.196:3000:0
[cardano_byron_proxy.diffusion:Debug:78] [2020-01-20 10:51:18.59 UTC] streamBlocks: Requesting stream of blocks from [d241cc87ef9d4ac5] to 0bdaaa4f

[cardano_byron_proxy.diffusion:Error:80] [2020-01-20 10:51:19.17 UTC] MsgStreamNoBlock handleStreamStart:strean Failed to find lca

[cardano_byron_proxy.diffusion.outboundqueue.self:Warning:75] [2020-01-20 10:51:19.17 UTC] sending MsgRequestBlocks (fromList [NodeId 13.250.233.196:3000:0]) to NodeId 13.250.233.196:3000:0 failed with BlockNetLogicException: DialogUnexpected "MsgStreamNoBlock handleStreamStart:strean Failed to find lca" :: SomeException
```

and then the `proxy` loops through these errors: 

```
[cardano_byron_proxy.diffusion.outboundqueue.self:Error:60] [2020-01-20 10:39:42.72 UTC] enqueue instruction EnqueueOne [NodeRelay,NodeCore] (MaxAhead 3) PHigh failed to enqueue message MsgRequestBlocks (fromList [NodeId 13.250.233.196:3000:0]) to forwarding sets [(NodeRelay,[NodeId 13.250.233.196:3000:0])]
[cardano_byron_proxy.main.client:Info:60] [2020-01-20 10:39:42.72 UTC] Attempting to download chain with hash AbstractHash 2be956e62cb1a52334a82ade9de04841ddac2082606ed1fa740d8bb039548381 from NodeId 13.250.233.196:3000:0
[cardano_byron_proxy.diffusion.outboundqueue.self:Debug:60] [2020-01-20 10:39:42.72 UTC] inFlight = fromList []
[cardano_byron_proxy.diffusion.outboundqueue.self:Debug:60] [2020-01-20 10:39:42.72 UTC] Rejected alternative NodeId 13.250.233.196:3000:0 as it has a recent failure
[cardano_byron_proxy.diffusion.outboundqueue.self:Error:60] [2020-01-20 10:39:42.72 UTC] enqueue instruction EnqueueOne [NodeRelay,NodeCore] (MaxAhead 3) PHigh failed to enqueue message MsgRequestBlocks (fromList [NodeId 13.250.233.196:3000:0]) to forwarding sets [(NodeRelay,[NodeId 13.250.233.196:3000:0])]
```

@jbgi noticed a difference in the way logs are written which suggests some behaviour has changed:

1.0.3:
```
Rollback Origin
Rollforward (Block {blockPointSlot = SlotNo {unSlotNo = 0}, blockPointHash = ByronHash {unByronHash = AbstractHash d241cc87ef9d4ac5d4359d22d2db1c83102affd1220dda7e3c1895f47b33c8e4}})
startNode, we are NodeId de1dcb38-6ba7-4b18-969d-e82f537f7c73
dnsSubscriptionWorker: valency 1
subscriptionWorker: subscribing to NodeId 52.68.30.216:3000:0
```

< 1.0.3
```
Rollback Origin
startNode, we are NodeId 74ab47b9-a48a-4f0e-95d4-a07c169b6f33
dnsSubscriptionWorker: valency 1
Seeding database with genesis
subscriptionWorker: subscribing to NodeId 52.68.30.216:3000:0
Rollforward (Block {blockPointSlot = SlotNo {unSlotNo = 0}, blockPointHash = ByronHash {unByronHash = AbstractHash b365f1be6863b453f12b93e1810909b10c79a95ee44bf53414888513fe172c90}})
```

### PR DESCRIPTION
**Pull request by mrBliss**
Fixes #87.

We'll add the real genesis EBB ourselves.

### CODE REVIEW

**Comment by mrBliss** [comment]
This builds further upon #91. However, stack wouldn't compile #91 for me:

```
Error: While constructing the build plan, the following exceptions were encountered:                                                     
                                                                                                                                         
In the dependencies for io-streams-1.5.1.0:                                                                                              
    network-3.1.0.1 from stack configuration does not match >=2.3 && <3.1  (latest matching version is 3.0.1.1)                          
needed due to cardano-byron-proxy-1.0.3 -> io-streams-1.5.1.0                                                                            
                                                                                                                                         
In the dependencies for io-streams-haproxy-1.0.1.0:                                                                                      
    network-3.1.0.1 from stack configuration does not match >=2.3 && <3.1  (latest matching version is 3.0.1.1)                          
needed due to cardano-byron-proxy-1.0.3 -> io-streams-haproxy-1.0.1.0                                                                    
                                                                                                                                         
In the dependencies for network-transport-tcp-0.7.0:                                                                                     
    network-transport-0.5.2 from stack configuration does not match >1.0                                                                 
needed due to cardano-byron-proxy-1.0.3 -> network-transport-tcp-0.7.0                                                                   
                                                                                                                                         
In the dependencies for servant-server-0.15:                                                                                             
    network-3.1.0.1 from stack configuration does not match >=2.8 && <2.9  (latest matching version is 2.8.0.1)                          
needed due to cardano-byron-proxy-1.0.3 -> servant-server-0.15                                                                           
                                                                                                                                         
In the dependencies for snap-core-1.0.4.0:                                                                                               
    network-3.1.0.1 from stack configuration does not match >=2.6 && <3.1  (latest matching version is 3.0.1.1)                          
needed due to cardano-byron-proxy-1.0.3 -> snap-core-1.0.4.0                                                                             
                                                                                                                                         
Some different approaches to resolving this:                                                                                             
                                                                                                                                         
  * Set 'allow-newer: true' in /home/thomas/.stack/config.yaml to ignore all version constraints and build anyway.                       
                                                                                                                                         
  * Recommended action: try adding the following to your extra-deps in /home/thomas/work/cardano-byron-proxy/stack.yaml:                 
                                                                                                                                         
- network-3.0.1.1@sha256:1a251b790ea98b6f7433f677958f921950780ba6f143d61ba8c0e3f7a9879097,4074                                           
                                                                                                                                         
Plan construction failed.                                                                               
```

I did not look into this further, *I'm just opening this PR to show how to fix #87*.

Because of the dependency bump of `ouroboros-network` in this PR, some more dependency bumps will need to be done, but I'll leave that to you @avieth :smile:.

**Comment by avieth** [comment]
@mrBliss in #91 I updated stack.yaml but not cardano.project. IIRC we have some tool that will automatically sync one to the other?

EDIT: oh but you were using stack? Hm. Builds with nix for me. I'll check it out.

**Comment by avieth** [comment]
So, [those changes I made to cardano-sl, so that it will build with network >= 3.0](https://github.com/input-output-hk/cardano-sl/pull/4269), actually do not build with stack or cabal, only with nix.

It is in some sense a false negative of cabal/stack: the packages *claim* their dependencies are incompatible, but I have proof that they aren't (at least as far as name resolution and type checking goes).

**Comment by avieth** [comment]
I can't figure out how to get the iohk-nix infrastructure to give me a nix-shell in which I have cabal and/or stack and can build with that. I'm waiting for somebody from the nix-tool team to advise me on slack but until then, maybe it's better if you @mrBliss or someone else who isn't on NixOS changes the library dependencies? It's just a matter of cross-checking them on hackage and picking ones that admit the new network library versions, and so on transitively.

**Comment by mrBliss** [comment]
@avieth This line https://github.com/avieth/network-transport-tcp/commit/984386467466d89621eda1cff8bbb435a9b9c0ef#diff-b1bb46cae6b083e0621ac9cde54958fbR29 looks wrong to me.

**Comment by mrBliss** [comment]
I have played about with the dependencies until stack only reported the following conflict (see comment above):

```
In the dependencies for network-transport-tcp-0.7.0:
    network-transport-0.5.2 from stack configuration does not match >1.0 
needed due to cardano-byron-proxy-1.0.3 -> network-transport-tcp-0.7.0
```

I added the following constraints to my `stack.yaml`:
```diff
@@ -130,6 +130,9 @@ extra-deps:
   - systemd-2.0.0
   - socks-0.6.0
   - connection-0.3.0
+  - io-streams-1.5.1.0
+  - io-streams-haproxy-1.0.1.0
+  - snap-core-1.0.4.0-r2
   - snap-server-1.1.1.1
   - swagger2-2.4
   # Needed by swagger2 version (InsOrd module)
@@ -137,10 +140,14 @@ extra-deps:
   # Neede because of swagger2
   - servant-swagger-1.1.7.1
   # Needed because of servant-swagger
-  - servant-0.15
-  - servant-client-0.15
-  - servant-client-core-0.15
-  - servant-server-0.15
+  - servant-0.16.1
+  - servant-client-0.16.0.1
+  - servant-client-core-0.16
+  - servant-server-0.16.1
+  - servant-blaze-0.9
+  - http-api-data-0.4.1.1
+  - time-compat-1.9.2.2
```

**Comment by avieth** [comment]
Oh yeah network-transport-tcp now has a > 1.0 constraint on network-transport. Weird, I didn't notice that... yet, I made that change in 984386467466d89621eda1cff8bbb435a9b9c0ef. 

Must have been a typo. There is no network-transport > 1.0. I'll fix it

**Comment by avieth** [comment]
I've got this branch building up to cardano-byron-proxy library (using nix) but it fails because of a change to the ChainDB API.

**Comment by mrBliss** [comment]
Closing because #89 will include the same fix.

**Pull request closed without merging**
