### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nc6**
Incorporates latest changes to ouroboros-network. In particular, the fix for mainnet syncing.

### CODE REVIEW

**Review by disassembler — APPROVED** [review]

**Review by mrBliss — CHANGES_REQUESTED** [review]
~We first need #17~

**Update**: I meant #32.

**Comment by nc6** [comment]
@mrBliss Yes, saw that one, think Bors has just merged it. Will update

**Review by mrBliss — APPROVED** [review]

**Pull request merged**
