### PR TITLE
Update for latest consensus (rewritten registry)

### PR DESCRIPTION
**Pull request by edsko**
This updates the proxy for the latest consensus (registry rewrite at https://github.com/input-output-hk/ouroboros-network/pull/961). Confirmed that this fixes the double CTRL-C problem that @mrBliss had identified.

### CODE REVIEW

**Comment by edsko** [comment]
Draft PR because the hash is the hash of my branch, might not be the hash once it gets merged to master.

**Comment by edsko** [comment]
This updated the byron proxy for both the rewritten registry and the recent changes to the chain state, but it depends on https://github.com/input-output-hk/ouroboros-network/pull/971 . Once that is merged, I will update this PR with the appropriate hash and we can merge this.

**Comment by edsko** [comment]
Ok, the necessary PRs have been merged into the `ouroboros-network` master branch. This is ready.

**Comment by avieth** [comment]
Oh I wish I saw this earlier. I just updated to latest ouroboros-network to fix the CTRL+C problem.

**Comment by avieth** [comment]
So you're the one who's been changing the import indentation

**Comment by edsko** [comment]
> So you're the one who's been changing the import indentation

Oh, apologies. I try to avoid it, I have to remember turning stylish-haskell off whenever I touch the ouroboros-network code. Apparently I forgot after all :/

**Comment by avieth** [comment]
> Oh, apologies. I try to avoid it, I have to remember turning stylish-haskell off whenever I touch the ouroboros-network code. Apparently I forgot after all :/

It only annoys me when there are conflicts.

**Comment by avieth** [comment]
I have a patch that makes this build. Will push it to this branch if you don't mind

**Comment by edsko** [comment]
Sure, go for it. As regards extra registry or not -- a local registry might ensure earlier deallocaton, but is not required anymore. See documentation of the (entirely rewritten) `ResourceRegistry`.

**Review by avieth — APPROVED** [review]

**Pull request merged**
