### PR TITLE
[DO NOT MERGE] stack.yaml:  add -O2 for "$everything"

### PR DESCRIPTION
**Pull request by deepfire**
..per https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-options

### CODE REVIEW

**Review by erikd — CHANGES_REQUESTED** [review]
This is not a request for a change. This is a "please do not do this until you prove to me that the pros far out weight the cons".

If we add this here, that means that *everybody* that builds this with `stack` suffers the potential slower build times that arise for `-O2`.

I will accept this this if:

* You provide benchmarks that show that `-O2` results in a significant performance improvement for the generated binary.
* You show that compile times are not significantly affected.

If you want `-O2` for a specific build you can add `-O2` on the stack command line (or Nix whatever) for a specific build. It should not be a default.

**Comment by mrBliss** [comment]
I agree with @erikd.

@deepfire I thought the conclusion of the discussion was: maybe we could enable `-O2` for *production builds* when *proven beneficial*.

This commit makes `-O2` the default. So I don't really understand why you're making this PR. I'm not a Nix expert, but maybe you want to populate the Nix cache with `-O2` artefacts so you don't have to locally recompile everything with `-O2`? :slightly_smiling_face:

**Comment by dcoutts** [comment]
Agree with @erikd and @mrBliss

**Comment by deepfire** [comment]
I should have made the PR's title more clear -- it was supposed to be an experimental playground branch/PR.

My apologies for the confusion.

**Pull request closed without merging**
